<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `FileParser.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once 'IceGrid/Admin.php';

if(!class_exists('IceGrid_ParseException'))
{
    class IceGrid_ParseException extends Ice_UserException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'IceGrid::ParseException';
        }

        public function __toString()
        {
            global $IceGrid__t_ParseException;
            return IcePHP_stringifyException($this, $IceGrid__t_ParseException);
        }

        public $reason;
    }

    $IceGrid__t_ParseException = IcePHP_defineException('::IceGrid::ParseException', 'IceGrid_ParseException', null, array(
        array('reason', $IcePHP__t_string)));
}

if(!interface_exists('IceGrid_FileParser'))
{
    interface IceGrid_FileParser
    {
        public function parse($xmlFile, $adminProxy);
    }

    class IceGrid_FileParserPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::IceGrid::FileParser', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IceGrid::FileParser', $facet);
        }
    }

    $IceGrid__t_FileParser = IcePHP_defineClass('::IceGrid::FileParser', 'IceGrid_FileParser', true, $Ice__t_Object, null, null);

    $IceGrid__t_FileParserPrx = IcePHP_defineProxy($IceGrid__t_FileParser);

    IcePHP_defineOperation($IceGrid__t_FileParser, 'parse', 2, 2, array($IcePHP__t_string, $IceGrid__t_AdminPrx), null, $IceGrid__t_ApplicationDescriptor, array($IceGrid__t_ParseException));
}
?>
