<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `FileInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once 'Ice/BuiltinSequences.php';

if(!class_exists('IcePatch2_FileInfo'))
{
    class IcePatch2_FileInfo
    {
        public function __construct($path='', $checksum=null, $size=0, $executable=false)
        {
            $this->path = $path;
            $this->checksum = $checksum;
            $this->size = $size;
            $this->executable = $executable;
        }

        public function __toString()
        {
            global $IcePatch2__t_FileInfo;
            return IcePHP_stringify($this, $IcePatch2__t_FileInfo);
        }

        public $path;
        public $checksum;
        public $size;
        public $executable;
    }

    $IcePatch2__t_FileInfo = IcePHP_defineStruct('::IcePatch2::FileInfo', 'IcePatch2_FileInfo', array(
        array('path', $IcePHP__t_string), 
        array('checksum', $Ice__t_ByteSeq), 
        array('size', $IcePHP__t_int), 
        array('executable', $IcePHP__t_bool)));
}

if(!isset($IcePatch2__t_FileInfoSeq))
{
    $IcePatch2__t_FileInfoSeq = IcePHP_defineSequence('::IcePatch2::FileInfoSeq', $IcePatch2__t_FileInfo);
}
?>
