<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `FileServer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once 'IcePatch2/FileInfo.php';

if(!isset($IcePatch2__t_ByteSeqSeq))
{
    $IcePatch2__t_ByteSeqSeq = IcePHP_defineSequence('::IcePatch2::ByteSeqSeq', $Ice__t_ByteSeq);
}

if(!class_exists('IcePatch2_PartitionOutOfRangeException'))
{
    class IcePatch2_PartitionOutOfRangeException extends Ice_UserException
    {
        public function __construct()
        {
        }

        public function ice_name()
        {
            return 'IcePatch2::PartitionOutOfRangeException';
        }

        public function __toString()
        {
            global $IcePatch2__t_PartitionOutOfRangeException;
            return IcePHP_stringifyException($this, $IcePatch2__t_PartitionOutOfRangeException);
        }
    }

    $IcePatch2__t_PartitionOutOfRangeException = IcePHP_defineException('::IcePatch2::PartitionOutOfRangeException', 'IcePatch2_PartitionOutOfRangeException', null, null);
}

if(!class_exists('IcePatch2_FileAccessException'))
{
    class IcePatch2_FileAccessException extends Ice_UserException
    {
        public function __construct($reason='')
        {
            $this->reason = $reason;
        }

        public function ice_name()
        {
            return 'IcePatch2::FileAccessException';
        }

        public function __toString()
        {
            global $IcePatch2__t_FileAccessException;
            return IcePHP_stringifyException($this, $IcePatch2__t_FileAccessException);
        }

        public $reason;
    }

    $IcePatch2__t_FileAccessException = IcePHP_defineException('::IcePatch2::FileAccessException', 'IcePatch2_FileAccessException', null, array(
        array('reason', $IcePHP__t_string)));
}

if(!interface_exists('IcePatch2_FileServer'))
{
    interface IcePatch2_FileServer
    {
        public function getFileInfoSeq($partition);
        public function getChecksumSeq();
        public function getChecksum();
        public function getFileCompressed($path, $pos, $num);
    }

    class IcePatch2_FileServerPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::IcePatch2::FileServer', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IcePatch2::FileServer', $facet);
        }
    }

    $IcePatch2__t_FileServer = IcePHP_defineClass('::IcePatch2::FileServer', 'IcePatch2_FileServer', true, $Ice__t_Object, null, null);

    $IcePatch2__t_FileServerPrx = IcePHP_defineProxy($IcePatch2__t_FileServer);

    IcePHP_defineOperation($IcePatch2__t_FileServer, 'getFileInfoSeq', 2, 1, array($IcePHP__t_int), null, $IcePatch2__t_FileInfoSeq, array($IcePatch2__t_PartitionOutOfRangeException));
    IcePHP_defineOperation($IcePatch2__t_FileServer, 'getChecksumSeq', 2, 1, null, null, $IcePatch2__t_ByteSeqSeq, null);
    IcePHP_defineOperation($IcePatch2__t_FileServer, 'getChecksum', 2, 1, null, null, $Ice__t_ByteSeq, null);
    IcePHP_defineOperation($IcePatch2__t_FileServer, 'getFileCompressed', 2, 1, array($IcePHP__t_string, $IcePHP__t_int, $IcePHP__t_int), null, $Ice__t_ByteSeq, array($IcePatch2__t_FileAccessException));
}

if(!interface_exists('IcePatch2_Admin'))
{
    interface IcePatch2_Admin
    {
        public function shutdown();
    }

    class IcePatch2_AdminPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::IcePatch2::Admin', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::IcePatch2::Admin', $facet);
        }
    }

    $IcePatch2__t_Admin = IcePHP_defineClass('::IcePatch2::Admin', 'IcePatch2_Admin', true, $Ice__t_Object, null, null);

    $IcePatch2__t_AdminPrx = IcePHP_defineProxy($IcePatch2__t_Admin);

    IcePHP_defineOperation($IcePatch2__t_Admin, 'shutdown', 0, 0, null, null, null, null);
}
?>
