<?php
// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `RouterF.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


if(!isset($Glacier2__t_Router))
{
    $Glacier2__t_Router = IcePHP_declareClass('::Glacier2::Router');
    $Glacier2__t_RouterPrx = IcePHP_defineProxy($Glacier2__t_Router);
}
?>
